version: '3.8'
services:
  server:
    build: .
    command: bash -c "cd /app && python3 server.py"
    volumes:
      - ./data:/app/data
    ports:
      - '5000:5000'
    deploy:
      resources:
        reservations:
          devices:
              - capabilities: [gpu]
  worker:
    build: .
    command: bash -c "cd /app && python3 worker.py"
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
              - capabilities: [gpu]
  redis:
    image: redis
    ports:
       - '5379:5379' 