version: '2'
services:
  server:
    build: .
    image: server-image
    command: bash -c "cd /app && python3 server.py"
    volumes:
      - .:/app
    ports:
      - '5000:5000'
  worker:
    image: server-image
    command: bash -c "cd /app && python3 worker.py"
    depends_on:
      - redis
    volumes:
      - .:/app
  redis:
    image: redis
    ports:
       - '5379:5379' 