version: '3.8'
services:
  worker:
    build: .
    command: bash -c "cd /app && python3 worker.py"
    volumes:
      - ./data:/app/data
      - ./tasks.py:/app/tasks.py
      - ./worker.py:/app/worker.py
    deploy:
      resources:
        reservations:
          devices:
              - capabilities: [gpu]